name: Update cars.csv daily

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          bash run_scraper.sh

      - name: Add timestamp to CSV
        run: |
          echo "Last updated: $(date)" >> cars.csv

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cars.csv
          git commit -m "Update cars.csv with new data and timestamp" || echo "No changes to commit"
          git push

